Vagrant.configure("2") do |config|
  config.vm.network "public_network", bridge: "wlp3s0"
  config.vm.box = "/home/kenfack/EASYTRaning.fr/vmbox/mondebian11.box"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "db-server"
    vb.memory = 512
    vb.cpus = 1

    config.vm.provision "shell", path: "provision-script.sh"

  end
end
